# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK_GeekBrains' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VK_GeekBrains
  pod 'RealmSwift', '~> 5.0.0'
  pod 'Firebase/Database'

end
